[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "quarto-book-template"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
render = "quarto render mybook --to html"

[dependencies]
quarto = ">=1.8.27,<2"
