project:
  type: book
  output-dir: docs

book:
  title: "Daily Stoic"
  author: "라이언 홀리데이, 스티븐 핸슬먼"
  date: "2026-01-31"
  chapters:
    - index.qmd
    - references.qmd

number-sections: false

bibliography: references.bib

format:
  html:
    theme:
      - default
      - brand

execute:
  freeze: auto

